
services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./demo
      dockerfile: Dockerfile
    container_name: springboot-backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/demo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend-SaaS/smart-dashboard-frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - app-network

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    networks:
      - app-network

  ai-assistant:
    build:
      context: ./ai-assistant/ai-backend
      dockerfile: Dockerfile
    container_name: ai-backend
    restart: always
    depends_on:
      - ollama
    ports:
      - "8000:8000"
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
    networks:
      - app-network

volumes:
  postgres-data:
  ollama:

networks:
  app-network:
    driver: bridge
